name: Docker Image CI

on: 
  push: 
    branched: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: using dpl to deploy to heroku
      run: |
        heroku git:remote -a drp43-website
        git push heroku main