name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        gem install dpl
        dpl --provider=heroku --app=<login>-simplewebapp --api-key=<heroku_api_key>

