name: Deploy

on: 
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - run: | 
          echo "in building stage"
          pip install -r requirements.txt

  test: 
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - uses: actions/checkout@v1
      - name: Installing pytest
        run: pip install -r requirements.txt
        
      - name: Executing pytest
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "drp43-website" #Must be unique in Heroku
          heroku_email: "tonyshengxue@outlook.com"
