name: Docker Image CI

on: 
  push: 
    branched: 
      - master

jobs:

  build:
    strategy: 
      ruby: 2.6

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: using dpl to deploy to heroku
      run: |
        gem install dpl
        dpl --provider=heroku --app=drp43-website --api-key=${{ secret.HEROKU_API_KEY }}

        