name: Docker Image CI

on: 
  push: 
    branched: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: using dpl to deploy to heroku
      run: |
        dpl --provider=heroku --app=drp43-website --api-key=${{ secrets.HEROKU_API_KEY }}